database:
  mysql:
    url: ""
    user: ""
    password: ""

# folder of plugin in template or default plugin folder for testing (.../plugins/[plugin name])
plugin-folder: ""

eventwarp: -1
normen-server: ""