database:
  mysql:
    url: ""
    user: ""
    password: ""

# folder of plugin in template or default plugin folder for testing (.../plugins/[plugin name])
plugin-folder: ""

normen:
  server: ""
  world: ""
  # default rotation of the player. Format: yaw/pitch. Default: 0/0
  rotation: ""